### PR TITLE
russian archer a6 v2 string

### PR DESCRIPTION
**Pull request by axet**
```
# strings ArcherA6v2_ru-up-ver1-3-3-P1\[20230808-rel60959\].bin  | grep special
{product_name:Archer A6,product_ver:2.0.0,special_id:52550000}
```

https://forum.openwrt.org/t/tp-link-archer-a6-v2-eu-ru-support/60075/50

firmware url:

* https://www.tp-link.com/ru/support/download/archer-a6/#Firmware

@svanheule Suggested-by?

### CODE REVIEW

**Comment by svanheule** [comment]
Thanks for the patch! No need to add my Suggested-by, as you suggested this change in the first place.

While the patch contents look good to me, there are formal issues with the commit message. See the wiki for more details: https://openwrt.org/submitting-patches#patch_checklist
Commit 02cdbc6a4d61605c008efef09162f772f553fcde is a very similar one, if you need an example.

**Comment by axet** [comment]
Ah, I could just type "Suggesded by". Ok . Never did that before.

**Comment by svanheule** [comment]
Thanks for the update!

I've updated the commit message to be more in line with the commit I referenced earlier.
Available with commit 5e14973d2199 ("tplink-safeloader: add Archer A6 v2 (RU)")

**Comment by axet** [comment]
No idea why. And how did it work before. But it seems this router need one more special_id to use with tftpd. Now my patch looks like this (basically copy of C6 with A6 name):

```diff
diff --git a/tplink-safeloader.c b/tplink-safeloader.c
index 53a42f7..3376ac8 100644
--- a/src/tplink-safeloader.c
+++ b/src/tplink-safeloader.c
@@ -1217,6 +1217,8 @@ static struct device_info boards[] = {
 		.vendor = "",
 		.support_list =
 			"SupportList:\r\n"
			"{product_name:Archer A6,product_ver:2.0.0,special_id:45550000}\r\n"
 			"{product_name:Archer C6,product_ver:2.0.0,special_id:45550000}\r\n"
+			"{product_name:Archer A6,product_ver:2.0.0,special_id:52550000}\r\n"
 			"{product_name:Archer C6,product_ver:2.0.0,special_id:52550000}\r\n"
+ 			"{product_name:Archer A6,product_ver:2.0.0,special_id:4A500000}\r\n",
 			"{product_name:Archer C6,product_ver:2.0.0,special_id:4A500000}\r\n",

```

**Comment by svanheule** [comment]
With 'tftp' you mean bootloader recovery using tftp? It might be that the FW checks for the "RU" ID (52550000), while the bootloader checks for the "JP" ID (4A500000).

Could you try tftp recovery using an image that only has the A6 v2 JP entry added, and not the RU entry? That way you can verify that the bootloader requires a different ID than the FW itself

**Comment by axet** [comment]
Just made full rebuild with only 0x4A500000 entry. And tftp recovery did accept the image. Strange. It used to work with 0x52550000. I'm only using tftp recovery flashing (and mtd write). No WEB flashing. I have one guess. Maybe I flash this router once by mistake with tl-wr842nd-v2 router firmware (same size).

```
       {
                .id     = "ARCHER-C6-V2",
                .vendor = "",
                .support_list =
                        "SupportList:\r\n"
                        "{product_name:Archer A6,product_ver:2.0.0,special_id:4A500000}\r\n",
                .part_trail = 0x00,
                .soft_ver = SOFT_VER_TEXT("soft_ver:1.9.1\n"),
```

**Comment by axet** [comment]
I'm not sure what is going on. I tried few rebuild using only:

1) 45550000 2) 52550000 3) 4A500000

Not flashing using tftp.

I also tried to build 52550000 + 4A500000 not flashing.

But when I all ALL of them A6 + C6 + 1+2+3 - it works. It could be more complicated combinations but I'm tiered rebuilding. I guess we could find out. But why not just add A6+JP?

**Comment by svanheule** [comment]
I can't find any firmware for Archer A6 v2 JP on TP-Link's website, and I would rather not add strings for devices of which we can't verify that the firmware images are compatible.

**Comment by axet** [comment]
Does this helps?

* https://www.tp-link.com/jp/support/download/archer-a6/#Firmware

**Comment by svanheule** [comment]
That's where I looked, but I don't see a v2...

**Comment by axet** [comment]
https://www.tp-link.com/jp/support/download/archer-a6/v3/#Firmware

v3 shows:

```
SupportList:
{product_name:Archer C6,product_ver:3.20,special_id:55530000}
{product_name:Archer C6,product_ver:3.20,special_id:45550000}
{product_name:Archer C6,product_ver:3.20,special_id:52550000}
{product_name:Archer C6,product_ver:3.20,special_id:4A500000}
{product_name:Archer C6,product_ver:3.20,special_id:4B520000}
{product_name:Archer A6,product_ver:3.20,special_id:45550000}
{product_name:Archer A6,product_ver:3.20,special_id:52550000}
{product_name:Archer C6,product_ver:3.0.0,special_id:42520000}
{product_name:Archer A6,product_ver:3.0.0,special_id:55530000}
{product_name:Archer A6,product_ver:3.0.0,special_id:54570000}
{product_name:Archer A6,product_ver:3.0.0,special_id:43410000}
{product_name:Archer A6,product_ver:3.0.0,special_id:4A500000}
```

**Comment by svanheule** [comment]
Sure, but the v3 is a different device. The flash layouts are not compatible, so adding one of those strings might result in a device that can't boot.

Is tftp the only recovery method you can use on the v2-RU? The forum thread also mentions an HTTP recovery. Does that accept an OpenWrt factory image with the only the RU ID added?

**Comment by axet** [comment]
1) wiki suggest tftp only (https://openwrt.org/toh/tp-link/archer_c6_v2) I tried once http, but it fails and i do not remember details.
2) bootstrap firmware from forum also has all a6+c6 special_ids, the only firmware I can flash using tftp, i guess that is not just me who can't flash anything else but bootstrap firmware (https://forum.openwrt.org/t/tp-link-archer-a6-v2-eu-ru-support/60075/14)
3) but I guess you are right, we need more prove this is not breaking other routers.

**Comment by axet** [comment]
I keep digging out why my device won't flash anything but A6+C6+EU+RU+JP firmwares. According to `target/linux/ath79/dts/qca9563_tplink_archer-c6-v2.dts` this device has readonly partition@7d0000 called "tplink" (I assume it never been changed by openwrt sysupgrade) which contains some device hard coded info about support list. Simple query shows that:

```
# strings /dev/mtd7 | grep special
{product_name:Archer A6,product_ver:2.0.0,special_id:45550000}
{product_name:Archer C6,product_ver:2.0.0,special_id:45550000}
{product_name:Archer A6,product_ver:2.0.0,special_id:52550000}
{product_name:Archer C6,product_ver:2.0.0,special_id:52550000}
{product_name:Archer A6,product_ver:2.0.0,special_id:4A500000}
{product_name:Archer C6,product_ver:2.0.0,special_id:4A500000}
```

Exactly same list as suggested by recent patch. A6+C6+EU+RU+JP.

Same when I query readonly partition@20000 called "info" I can see that is RU hardware version:

```
# strings /dev/mtd1|grep specia
special_id:52550000
```

**Pull request closed without merging**
