### PR TITLE
Bug-12939 - Add device info for Canadian CPE510

### PR DESCRIPTION
**Pull request by mungewell**
https://github.com/openwrt/openwrt/issues/12939

### CODE REVIEW

**Comment by Djfe** [comment]
You could also add this one to v1:
`CPE520(TP-LINK|CA|N300-5):1.1`

and these ones to v2
```
"CPE510(TP-LINK|CA|N300-5|43410000):2.0\r\n"
"CPE520(TP-LINK|CA|N300-5|43410000):2.0\r\n"
```

and maybe also these ones to v2:
(I haven't found these in a file but the code appears to duplicate entries to have the IDs for all countries not the one they are found with)
```
"CPE510(TP-LINK|EU|N300-5|43410000):2.0\r\n"
"CPE510(TP-LINK|UN|N300-5|43410000):2.0\r\n"
"CPE510(TP-LINK|US|N300-5|43410000):2.0\r\n"
"CPE510(TP-LINK|CA|N300-5):2.0\r\n"
```

CPE520 v2 doesn't appear to be supported, yet. (So I didn't add those entries to the safeloader)

**Comment by svanheule** [comment]
The patch contents look fine, but there are formal issues. You need a proper commit title, message and Signed-off-by: tag as described at https://openwrt.org/submitting-patches. You can also look at previous commits (e.g. 17ca5eeb1c10a12766424f46af52f207eca6c4e0) for some examples.

The link to the bug report can  be added with a Link: tag, if you like.

**Comment by Djfe** [comment]
Do you know how to edit your commit?
In-case you need help:
```
git commit --amend --signoff
git push -f
```
in-case that you also edited a file:
```
git commit -a --amend --signoff
git push -f
```

**Comment by lynxis** [comment]
Merged but with different commit message.

**Comment by dkbiz83** [comment]
Hi guys, is there a chance you could help me add similar support of the Canadian version to CPE710?

**Pull request closed without merging**
